apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: dev-persistent-cluster
  namespace: kafka-workspace
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      # inter.broker.protocol.version: '3.3'
    resources: {}
      # limits: 
      #   cpu: 1500m
      #   memory: 1500Mi
      # requests:
      #   cpu: 1000m
      #   memory: 1000Mi
    storage:
      type: persistent-claim
      size: 7Gi
      class: lvms-vg1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9093
        type: route
        tls: true
    version: 3.4.0
    replicas: 3
  entityOperator:
    topicOperator: {}
    userOperator: {}
  zookeeper:
    resources: {}
      # limits: 
      #   cpu: 700m
      #   memory: 200Mi
      # requests:
      #   cpu: 500m
      #   memory: 50Mi
    storage:
      type: persistent-claim
      class: lvms-vg1
      size: 7Gi
    replicas: 3